name: rfi-downloader
channels:
  - conda-forge
dependencies:
  - python>=3.8
  - gtk4
  - pygobject
  - setuptools
  - pip
  - adwaita-icon-theme
  - librsvg
  - libsoup
  - bugsnag
  - humanfriendly
